FROM sitespeedio/webbrowsers:firefox-49.0-chrome-54.0

RUN useradd --user-group --create-home --shell /bin/false app

ENV HOME=/usr/src/app

# Create app directory
WORKDIR $HOME

RUN chown -R app:app $HOME

USER app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

# Bundle app source
COPY . .

EXPOSE 8080
# CMD [ "node", "index.js" ]

ENTRYPOINT ["./start.sh"]



# FROM jrottenberg/ffmpeg:4.2-scratch AS ffmpeg
# FROM node:12
# COPY --from=ffmpeg / /

# RUN apt-get update && apt-get install -y chromium xvfb

# WORKDIR /usr/src/app

# # RUN apt-get update
# # RUN apt-get install ffmpeg

# COPY package*.json ./
# RUN npm install
# COPY . .

# EXPOSE 8080

# CMD [ "node", "index.js" ]